config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'pages/index'
  root :to => "pages#index"
    
  scope "/:locale", :locale => /en|ru/ do
    # devise_for :users
    # devise_for :users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    
    resources :units
    
    resources :news do
          get 'page/:page', :action => :index, :on => :collection
    end
    
    resources :categories do 
      get 'page/:page' => 'categories#index', :action => :index, :on => :collection
    end
    
    
    get 'pages/*page' => 'pages#index', :as => 'pages'
    
  end
end

app/views/shared/_left_menu.html.slim
ul.nav.nav-list
  - @left_items.each do |item|
    li = link_to item.menu_name, pages_path(item)

app/views/shared/_news.html.erb
<!--span class="date"><%= news.date %></span-->
<h3 class="newsflash-title"><%= link_to news.head, news %></h3>

app/views/shared/_news_anounce.html.erb
<li class="news_anounce_element">
    <div>
      <div class="date">
        <div class="day">
          <%= l news_anounce.date, format: :day %>
        </div>
        <div class="month">
          <%= l news_anounce.date, format: :month %>
        </div>
        
        <div class="bot_arrow">
        </div>
      </div>
      

    </div>
    
    <div class='lining' style="width:220px !important">

      <div class="anounce">
        <%= link_to news_anounce  do %>
          <%= news_anounce.anounce.truncate(90) %>
        <% end %>
      </div>
    </div>
</li>

app/views/shared/_top_menu.html.slim
ul.nav
  - @top_items.each do |item|
    li = link_to item.menu_name, pages_path(item)