config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  get 'pages/index'
  root :to => "pages#index"
    
  scope "/:locale", :locale => /en|ru/ do
    # devise_for :users
    # devise_for :users, ActiveAdmin::Devise.config
    # ActiveAdmin.routes(self)
    
    resources :units
    
    resources :news do
          get 'page/:page', :action => :index, :on => :collection
    end
    
    resources :categories do 
      get 'page/:page' => 'categories#index', :action => :index, :on => :collection
    end
    
    
    get 'pages/*page' => 'pages#index', :as => 'pages'
    
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  paginates_per 10
  
  # collection_action :index, :method => :get do
  #   scope = News.scoped
  #   @collection = scope.page() if params[:q].blank?
  #   @search = scope.metasearch(clean_search_params(params[:q]))
  # end
  
  def to_param
    [id, head.parameterize].join("-")
  end


  def next
    News.where("id > ?", id).order("id ASC").first
  end

  def prev
    News.where("id < ?", id).order("id DESC").first
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show]
  before_action :set_news_for_calendar, only: [:index]
  # GET /news
  # GET /news.json
  def index
    if params[:date].present?
      @search = News.search({date_gt: Time.parse(params[:date]).beginning_of_day, date_lt: Time.parse(params[:date]).end_of_day})
    elsif params[:month].present?
      @search = News.search({ date_gt: Time.parse(params[:month]).beginning_of_month, date_lt: Time.parse(params[:month]).end_of_month})
    else 
      @search = News.order("date desc").search()
    end
    @news = @search.result.page(params[:page])
    # @news = @news.where("created_at = ?", params[:date].to_date) if params[:date]
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # # GET /news/new
  # def new
  #   @news = News.new
  # end
  # 
  # # GET /news/1/edit
  # def edit
  # end

  # POST /news
  # POST /news.json
  # def create
  #   @news = News.new(news_params)
  # 
  #   respond_to do |format|
  #     if @news.save
  #       format.html { redirect_to @news, notice: 'News was successfully created.' }
  #       format.json { render :show, status: :created, location: @news }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @news.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  # def update
  #   respond_to do |format|
  #     if @news.update(news_params)
  #       format.html { redirect_to @news, notice: 'News was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @news }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @news.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /news/1
  # DELETE /news/1.json
  # def destroy
  #   @news.destroy
  #   respond_to do |format|
  #     format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end
    
  def set_news_for_calendar
    #@news_calendar = params[:month] ? News.search({ date_gt: params[:month].to_date.beginning_of_month, date_lt: params[:month].to_date.end_of_month}).result.to_a : News.last(100
    #@news_calendar = News.where("date > ? AND date < ?", Time.parse(params[:month]).beginning_of_month, Time.parse(params[:month]).end_of_month)
    if params[:month].present?
      @news_cal = News.search({ date_gt: Time.parse(params[:month]).beginning_of_month, date_lt: Time.parse(params[:month]).end_of_month}).result
    else
      @news_cal = News.last(200)
    end
    #@news_calendar = News.all
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def news_params
    #   params.require(:news).permit(:date, :title, :keywords, :description, :url, :head, :anounce, :body, :status)
    # end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_calendar.html.erb
<div class='calendar'>
  <%= calendar_for(@news_cal) do |calendar| %>
    <h2 id="month">
      <%= link_to "<", controller: 'news', action: 'index', month: (@date.beginning_of_month-1) %>
      <%= I18n.t("date.month_names")[@date.strftime("%m").to_i] %>
      <%= link_to ">", controller: 'news', action: 'index', month: (@date.end_of_month+1) %>
    </h2>
    <%= calendar.head('Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб') %>
    <% calendar.day(day_method: :date) do |date, nws| %>
      <% if nws.count != 0 %>
        <%= link_to date.day, news_index_path(date: (@date.to_date.beginning_of_month-1 + date.day), month: params[:month]) %>
      <% else %>
        <% date.day %>
        <%= link_to date.day, news_index_path(date: (@date.to_date.beginning_of_month-1 + date.day), month: params[:month]) %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/news/_news.html.erb
<div class="news">
    

  <div class="cont">
    <h2><%= link_to news.head, news, class: 'header_in_index' %></h2>
    <p class="anounce"><%= news.anounce %></p>
  </div>
</div>

app/views/news/index.html.erb
<% content_for :header_title  do %>
  <h1>Новости</h1>
<% end %>
<!-- <h1>Новости</h1> -->

<% if @news.to_a.size > 0 %>
  <% @news.group_by { |item| item.date.to_date.strftime("%d %b") }.each_pair do |date, news| %>
    <div class="news">
      <span class="date">
        <%= link_to  news_index_path(date: date), class: 'time_in_index' do %>
          <span class="rel"><%= l date.to_date, format: :for_news %></span>
        <% end %>
      </span>
    </div>
    <% news.each do |n| %>
      <%= render n %>
    <% end %>

  <% end %>

  <br><br>

  <%= paginate @news %>
<% else %>
  <p>В указанный период новостей нет</p>
<% end %>

app/views/news/show.html.erb
<% content_for(:header_title) do %>
  <%= link_to "< назад к списку новостей", news_index_path, class: '' %>
<% end %>

<% content_for(:title) do %>
  <%= @news.head %>
<% end %>

<div class='news shadowed' style="padding: 15px;">
  <span class="time"><%= l @news.created_at, format: :long %></span>

  <h2 class="header"><%= @news.head %></h2>
  <p><%= @news.body %></p>
  <br>
  <hr>
  <div class="right" style="text-align:right;">
    <p class='time'>Последнее изменение: <%= l @news.updated_at, format: :long %></p>
  </div>
</div>